# Generated by Django 3.0.5 on 2020-04-27 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('picture_1', models.CharField(max_length=512)),
                ('picture_2', models.CharField(max_length=512)),
                ('picture_3', models.CharField(max_length=512)),
                ('picture_4', models.CharField(max_length=512)),
                ('picture_5', models.CharField(max_length=512)),
                ('picture_6', models.CharField(max_length=512)),
                ('picture_7', models.CharField(max_length=512)),
                ('picture_8', models.CharField(max_length=512)),
                ('picture_9', models.CharField(max_length=512)),
                ('picture_10', models.CharField(max_length=512)),
                ('picture_11', models.CharField(max_length=512)),
                ('picture_12', models.CharField(max_length=512)),
                ('picture_13', models.CharField(max_length=512)),
                ('picture_14', models.CharField(max_length=512)),
                ('picture_15', models.CharField(max_length=512)),
                ('picture_16', models.CharField(max_length=512)),
                ('picture_17', models.CharField(max_length=512)),
                ('picture_18', models.CharField(max_length=512)),
                ('picture_19', models.CharField(max_length=512)),
                ('picture_20', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
