# Generated by Django 3.0.5 on 2020-04-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200427_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture_10',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_11',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_12',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_13',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_14',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_15',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_16',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_17',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_18',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_19',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_2',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_20',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_3',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_4',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_5',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_6',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_7',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_8',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_9',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
